### PR TITLE
Implement Display scoring support

### PR DESCRIPTION
**Pull request by jsm174**
This PR is to support https://github.com/freezy/VisualPinball.Engine/issues/421 and https://github.com/freezy/VisualPinball.Engine/pull/435.

It adds the following units:

- `ClearDisplayUnit`
- `AddPointsDisplayUnit`
- `DisplayScoreEventUnit`

## `ClearDisplayUnit`

Screen_Shot_2022-08-26_at_5 30 52_PM

This unit can be used to clear a display. For a `ScoreReelDisplayComponent`, if it is connected to a `ScoreMotorComponent`, the reels will be advanced in a sequence. 

For example, if the score is 4805, the score advance sequence will be: 5906, 6007, 7008, 8009, 9000, 0.

## `AddPointsDisplayUnit`

Screen_Shot_2022-08-26_at_5 31 51_PM

This unit accepts an incoming points amount, and if the display is connected to a `ScoreMotorComponent` increases the score appropriately. For example, if the points are 500, and the Score Motor is not running, the score reels will be advanced 5 times, (100 points per advance).

## `DisplayScoreEventUnit`

This unit receives updated score events from the connected display. The score can then be saved into a Player variable, or used to drive an additional display.

Screen_Shot_2022-08-26_at_5 33 31_PM

### 

Since only `ScoreReelDisplayComponent` can keep track of scores, we needed to add a `Display Type` to `Visual Scripting Displays`:

Screen_Shot_2022-08-26_at_5 35 11_PM

### CODE REVIEW

**Comment by jsm174** [comment]
After discussions on Discord, @freezy suggested using the existing `Update Display` unit instead of an additional `Add Points` unit.

I've refactored the code accordingly, and it really makes everything a lot cleaner. 

We are now only adding two nodes, `Display Update Event` and `Clear Display`.

`Display Update Event` triggers when the display has been updated. If the display is a Score Reel, it will have a Numeric output which is the Score Reel's internal score.  This internal score can then be used to set the player's score variable.

Note, the internal score may be greater than the amount of reels.  

Here is an example of updating reels, capturing the score, and then sending that score to a segment display:

Screen Shot 2022-08-28 at 1 51 54 PM

**Comment by jsm174** [comment]
@freezy - when you have free time, can we get an Display Update Event icon with the lightning bolt?

**Review by freezy — APPROVED** [review]
Looking good!

I guess now we need an "interruptor" node so we can turn off some lights in Volley when the motor is running?

**Comment by jsm174** [comment]
I think we can look at the motor running switch to accomplish that.

**Comment by jsm174** [comment]
I think we can look at the motor running switch to accomplish that.

**Comment by freezy** [comment]
Yes, the interruptor would take in the motor switch and the light status and its output is then wired to the light.

**Comment by jsm174** [comment]
Interesting. I was thinking of just taking the lighting graph and toggling the specific light variables volley uses. 

That would be a useful unit.

**Pull request merged**
